version: "3.8"
services:
  frontend:
    image: lofowebteam/tpc_portal_frontend:a2f618a3155474d8b7846826e3af89a8ab00f307
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  backend:
    image: lofowebteam/tpc_portal_backend:d335fa92ed4d77ee71ad93817a68d54d68a745f1
    restart: always
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - 5000:5000
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 5432:5432
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    # ports:
    #   - 5432:5432
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
