version: "3.8"
services:
  frontend:
    image: lofowebteam/tpc_portal_frontend:b8a97c84b67403120a114ef5d4a492dd78ef9855
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  backend:
    image: lofowebteam/tpc_portal_backend:c33e7187b975035aeafffc76af5cac049ca46f8f
    restart: always
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - 5000:5000
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/tpc.iiti.ac.in/fullchain.pem:/cert/fullchain.pem
      - /etc/letsencrypt/live/tpc.iiti.ac.in/privkey.pem:/cert/privkey.pem
    ports:
      - 80:80
      - 443:443
      - 5432:5432
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    # ports:
    #   - 5432:5432
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
