name: ssh-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ssh pipeline
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          script: |
            commit_hash=${{ github.head_ref }}.${{ github.sha }}
            echo "Hello from commit $commit_hash" > ~/Documents/hello.txt