name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - 'nginx.conf'
      - 'pg_hba.conf'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on remote
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        env:
          BUILD_DIR: "~/tpc_portal"
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          envs: BUILD_DIR
          script: |
            cd ~/tpc_portal && touch iamhere.txt
            echo "$BUILD_DIR" > build_dir.txt
