name: Configuration change deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - 'nginx.conf'
      - 'pg_hba.conf'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on remote
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        env:
          BUILD_DIR: "~/tpc_portal"
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          script: |
            cd $BUILD_DIR
            pwd
            git pull origin main
            docker compose up -d --no-deps --build
